### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by crobinson42** [AmericanSolutions/company-www#13]
add favicon

**Comment by crobinson42** [comment]
Use this http://www.favicon.cc/?action=icon&file_id=53607

**Comment by wingchunkf** [comment]
The favicon was added/pushed via the sass_variables branch. PR #42

**Comment by crobinson42** [comment]
reopening because the sass branch was closed and not being used since the latest template push to the repo won't also use the sass variables created.

**Comment by wingchunkf** [comment]
Favicon added via google_analytics branch.

**Comment by crobinson42** [comment]
@wingchunkf we're not getting the favicon? You can open your console in the dev env and see this:

`16:34:31.666 /favicon.ico Failed to load resource: the server responded with a status of 404 ()`

**Comment by wingchunkf** [comment]
Fixed on merge #52.
