### ISSUE TITLE
assets $SCHEME

### ISSUE THREAD

**Issue by crobinson42** [AmericanSolutions/company-www#17]
We need all assets to be included the same as the current url scheme:

The most development env and production friendly method is to use `//...url` instead of a fixed `http://...` or `https://...` because running the local dev server won't be over https, it may cause errors. Using `//...` will cause the resource to be requested over the current http "scheme".

![screenshot 2017-08-23 18 21 08](https://user-images.githubusercontent.com/5973579/29645124-3797c718-8830-11e7-91fc-e576fc796c59.png)

**Comment by wingchunkf** [comment]
This task was completed on the assets_scheme branch.
