### ISSUE TITLE
[Design] Header section

### ISSUE THREAD

**Issue by crobinson42** [AmericanSolutions/company-www#18]
![screenshot 2017-08-23 19 00 25](https://user-images.githubusercontent.com/5973579/29645968-58f34ef0-8835-11e7-9618-8ff3b31be614.png)

This section needs some thought on the cover image if we're going to change it or add opacity or  simply tint.

Title needs to be captivating - possibly something w/ animation that drops the title in.

Sub-title - also captivating and possibly dynamic content.

**Comment by wingchunkf** [comment]
Created header_section branch for title(s) and cover image work.
