### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by crobinson42** [AmericanSolutions/company-www#8]
setup GA and create a GA custom events task

- [x] setup GA

> Note: we need to add logic in the GA js file or script that DOES NOT activate GA if the domain is in our "dev environment", ie: the page is being loaded on dev.americandevshop.com

**Comment by crobinson42** [comment]
@wingchunkf What's the status with this and is there a PR or branch coming? Please see added notes to task above.

**Comment by wingchunkf** [comment]
I've added an event_tracking branch and conditional logic to exclude the dev.americandevshop.com environment. GA tracking code is UA-105525048-1.
